/**
 * Slack API
 * The slack API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Message } from './message';


export interface Conversation { 
    id: string;
    directMessage: boolean;
    name: string;
    participants: Array<User>;
    messages: Array<Message>;
}

