/**
 * Slack API
 * The slack API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Conversation } from './conversation';


export interface Message { 
    conversation: Conversation;
    user: User;
    text: string;
    createAt: Date;
    updateAt: Date;
}

